name: SSHPASS Github Action
inputs:
  host:
    description: "SSHPASS host"
    required: true
  username:
    description: "SSHPASS username"
    required: true
  password:
    description: "SSHPASS password"
    required: true
  port: 
    description: "PORT password"
    required: false
    default: 22
  run:
    description: "SSHPASS commands to run"
    required: true

description: 'SSHPASS Github Action'
branding:
  icon: dollar-sign
  color: gray-dark
runs-on: ubuntu-18.04
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.host }}
  - ${{ inputs.username }}
  - ${{ inputs.password }}
  - ${{ inputs.port }}
  - ${{ inputs.run }}
